//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultationSet
    {
        public int Id { get; set; }
        public string date { get; set; }
        public string actNature { get; set; }
        public double cost { get; set; }
        public int FileId { get; set; }
    
        public virtual FileSet FileSet { get; set; }
    }
}
