//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthCareEntities3 : DbContext
    {
        public HealthCareEntities3()
            : base("name=HealthCareEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CitySet> CitySets { get; set; }
        public virtual DbSet<ConsultationSet> ConsultationSets { get; set; }
        public virtual DbSet<FileSet> FileSets { get; set; }
        public virtual DbSet<RDVSet> RDVSets { get; set; }
        public virtual DbSet<UserSet> UserSets { get; set; }
        public virtual DbSet<PatientSet> PatientSets { get; set; }
    }
}
