//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientSet()
        {
            this.RDVSets = new HashSet<RDVSet>();
        }
    
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public string CellPhone { get; set; }
        public string Address { get; set; }
        public int Id { get; set; }
        public Nullable<int> CitySetId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDVSet> RDVSets { get; set; }
        public virtual CitySet CitySet { get; set; }
        public virtual FileSet FileSet { get; set; }
    }
}
